2021-10-07 14:49:33.494 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:49:33.691 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:49:33.753 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-10-07 14:49:34.312 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=559.12[ms]
2021-10-07 14:49:34.557 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=866.15[ms]
2021-10-07 14:49:34.567 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-10-07 14:49:47.184 - CRITICAL - 2445 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-10-07 14:49:47.201 - WARNING - 2445 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.34.0.post1'. Please install 'azureml-train-automl-runtime==1.34.0.post1' (e.g. `pip install azureml-train-automl-runtime==1.34.0.post1`) and then rerun the previous command.
2021-10-07 14:49:47.213 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=12645.02[ms]
2021-10-07 14:49:47.214 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=13719.23[ms]
2021-10-07 14:50:13.488 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:50:13.517 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:50:13.541 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-10-07 14:50:14.035 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=493.41[ms]
2021-10-07 14:50:14.246 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=728.65[ms]
2021-10-07 14:50:14.247 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-10-07 14:50:18.152 - CRITICAL - 2445 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-10-07 14:50:18.161 - WARNING - 2445 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.34.0.post1'. Please install 'azureml-train-automl-runtime==1.34.0.post1' (e.g. `pip install azureml-train-automl-runtime==1.34.0.post1`) and then rerun the previous command.
2021-10-07 14:50:18.178 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=3931.2[ms]
2021-10-07 14:50:18.179 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=4691.34[ms]
2021-10-07 14:56:39.418 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:56:39.443 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-10-07 14:56:39.467 - INFO - 2445 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-10-07 14:56:40.013 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=545.61[ms]
2021-10-07 14:56:40.230 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=786.42[ms]
2021-10-07 14:56:40.231 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-10-07 14:56:49.410 - CRITICAL - 2445 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'pinvh' from 'sklearn.utils.fixes' (/home/ebbe/miniconda3/envs/azure/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "_model_download_utilities.py", line 183, in _load_automl_model
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 15, in <module>
    from azureml.automl.runtime._engineered_feature_names import (_FeatureTransformers, _GenerateEngineeredFeatureNames,
  File "_engineered_feature_names.py", line 14, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 11, in <module>
    from ._bayes import BayesianRidge, ARDRegression
  File "_bayes.py", line 16, in <module>
    from ..utils.fixes import pinvh

ExceptionTarget: Unspecified
2021-10-07 14:56:49.992 - CRITICAL - 2445 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'pinvh' from 'sklearn.utils.fixes' (/home/ebbe/miniconda3/envs/azure/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    except Exception as e:
  File "_model_download_utilities.py", line 91, in _download_automl_model
  File "_model_download_utilities.py", line 183, in _load_automl_model
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 15, in <module>
    from azureml.automl.runtime._engineered_feature_names import (_FeatureTransformers, _GenerateEngineeredFeatureNames,
  File "_engineered_feature_names.py", line 14, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 11, in <module>
    from ._bayes import BayesianRidge, ARDRegression
  File "_bayes.py", line 16, in <module>
    from ..utils.fixes import pinvh

ExceptionTarget: Unspecified
2021-10-07 14:56:49.993 - INFO - 2445 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=9762.02[ms]
2021-10-07 14:56:49.995 - CRITICAL - 2445 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: ImportError
Message: cannot import name 'pinvh' from 'sklearn.utils.fixes' (/home/ebbe/miniconda3/envs/azure/lib/python3.8/site-packages/sklearn/utils/fixes.py)
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    except Exception as e:
  File "run.py", line 719, in get_output
  File "_model_download_utilities.py", line 91, in _download_automl_model
  File "_model_download_utilities.py", line 183, in _load_automl_model
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 15, in <module>
    from azureml.automl.runtime._engineered_feature_names import (_FeatureTransformers, _GenerateEngineeredFeatureNames,
  File "_engineered_feature_names.py", line 14, in <module>
    from sklearn.cluster import MiniBatchKMeans
  File "__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "__init__.py", line 11, in <module>
    from ._bayes import BayesianRidge, ARDRegression
  File "_bayes.py", line 16, in <module>
    from ..utils.fixes import pinvh

ExceptionTarget: Unspecified
2021-10-07 14:56:49.997 - INFO - 2445 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=10579.1[ms]
